# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ ... }:
{
  flake.modules.nixos.vrynHardwareConfiguration =
    {
      lib,
      modulesPath,
      ...
    }:

    {
      imports = [
        (modulesPath + "/profiles/qemu-guest.nix")
      ];

      boot.initrd.availableKernelModules = [
        "virtio_pci"
        "virtio_scsi"
        "ahci"
        "sd_mod"
      ];
      boot.initrd.kernelModules = [ ];
      boot.kernelModules = [ ];
      boot.extraModulePackages = [ ];
      fileSystems."/" = {
        device = "/dev/sda";
        fsType = "ext4";
      };
      swapDevices = [
        { device = "/dev/sdb"; }
      ];
      boot.kernelParams = [ "console=ttyS0,19200n8" ];
      boot.loader = {
        timeout = 10;
        grub = {
          enable = true;
          forceInstall = true;
          device = "nodev";
          extraConfig = ''
            serial --speed=19200 --unit=0 --word=8 --parity=no --stop=1;
            terminal_input serial;
            terminal_output serial
          '';
        };
      };
      networking = {
        usePredictableInterfaceNames = false;
        useDHCP = lib.mkDefault false;
        interfaces.eth0.useDHCP = lib.mkDefault true;
      };
      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    };
}
